services:
  database:
    container_name: postgres_local
    image: postgres:15-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data:
    external: false
