# Construir modulos
FROM node:23-alpine as dev
WORKDIR /app
COPY package.json package.json
COPY yarn.lock yarn.lock
RUN yarn install --frozen-lockfile


# Construir app
FROM node:23-alpine as builder
WORKDIR /app
COPY --from=dev /app/node_modules ./node_modules
COPY . .
RUN npx tsc

# Preparar produccion
FROM node:23-alpine as prod
WORKDIR /app
COPY package.json package.json
COPY yarn.lock yarn.lock
RUN yarn install --prod --frozen-lockfile

# Correr la app
FROM node:23-alpine as runner
WORKDIR /app
EXPOSE 3000
COPY --from=prod /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist
COPY public/ ./public
ENV PORT=3000
ENV NODE_ENV="production"
EXPOSE 3000
CMD ["node","dist/main.js"]
