FROM  node:19.2-alpine3.16 as builder
WORKDIR /app
COPY package.json ./
RUN yarn


FROM  node:19.2-alpine3.16 as setup
WORKDIR /app
COPY --from=builder /app/node_modules ./node_modules
COPY . .
RUN yarn build


FROM  node:19.2-alpine3.16 as runner
WORKDIR /app
COPY package.json ./
RUN yarn --prod && rm -rf package.json
COPY --from=setup /app/dist ./dist
RUN ls -a
CMD [ "node"        ,       "dist/index.js" ]

