version: '3'

services:
  app:
    container_name: express_mongo
    build:
      context: .
      dockerfile: Dockerfile
    image: zero0242/node-mongo-api:1.0.0
    restart: always
    depends_on:
      - mongoDB
    ports:
      - "${PORT}:3000"
    environment:
      NODE_ENV: ${NODE_ENV}
      MONGO_DBNAME: ${MONGO_DBNAME}
      MONGO_CNN: ${MONGO_CNN}
      JWT_KEY: ${JWT_KEY}
      JWT_DURATION: ${JWT_DURATION}

  mongoDB:
    container_name: ${MONGO_DBNAME}
    image: mongo:6.0
    volumes:
      - mongodata:/data/db
    restart: always
  mongoExpress:
    depends_on:
      - mongoDB
    container_name: mongoPanel
    image: mongo-express:1.0.0-alpha.4
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=${MONGO_DBNAME}
    restart: always

volumes:
  mongodata:
