# Construir modulos
FROM node:19.2-alpine3.16 as dev
WORKDIR /app
COPY package.json package.json
RUN yarn install --frozen-lockfile


# Construir app
FROM node:19.2-alpine3.16 as builder
WORKDIR /app
COPY --from=dev /app/node_modules /node_modules
COPY . .
RUN npx tsc

# Preparar produccion
FROM node:19.2-alpine3.16 as prod
WORKDIR /app
COPY package.json package.json
RUN yarn install --prod --frozen-lockfile

# Correr la app
FROM node:19.2-alpine3.16 as runner
WORKDIR /app
EXPOSE 3000
COPY --from=prod /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist
COPY public/ ./public
CMD ["node","dist/index.js"]
