version: '3'

services:
  mongoDB:
    container_name: ${MONGO_DBNAME}
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    restart: always
  mongoExpress:
    depends_on:
      - mongoDB
    container_name: mongoPanel
    image: mongo-express:1.0.0-alpha.4
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=${MONGO_DBNAME}
    restart: always

volumes:
  mongodata: